---
- name: Copy K3s service file
  template:
    src: 'k3s.service.j2'
    dest: '{{ systemd_dir }}/k3s-node.service'
    owner: root
    group: root
    mode: 0755

- name: Enable and check K3s service
  systemd:
    name: k3s-node
    daemon_reload: yes
    state: restarted
    enabled: yes

- name: Create kubectl symlink
  file:
    src: /usr/local/bin/k3s
    dest: /usr/local/bin/kubectl
    state: link

- name: Create crictl symlink
  file:
    src: /usr/local/bin/k3s
    dest: /usr/local/bin/crictl
    state: link

- name: Create ctr symlink
  file:
    src: /usr/local/bin/k3s
    dest: /usr/local/bin/ctr
    state: link

- name: Copy k3s-killall.sh to /usr/local/bin
  copy:
    src: k3s-killall.sh
    dest: /usr/local/bin/k3s-killall.sh
    owner: root
    group: root
    mode: 'u=rwx,g=rx,o=rx'

- name: Copy k3s-agent-uninstall.sh to /usr/local/bin
  template:
    src: k3s-agent-uninstall.sh.j2
    dest: /usr/local/bin/k3s-agent-uninstall.sh
    owner: root
    group: root
    mode: 0755
